### ISSUE TITLE
Re-enable coercions

### ISSUE THREAD

**Issue by kjetilk** [kasei/perl-iri#13]
Currently, the coercions from `Str` and `URI` are [commented out](https://github.com/kasei/perl-iri/blob/master/lib/IRI.pm#L89-L91), and they are missed. 

In particular, in Attean, when using `URI::Namespace`, I have to do 
```perl
Attean::IRI->new($ns->foaf->name->as_string);
```
and it feels a bit ugly to explicitly go through a string for conversion between two very similar types. So, it seems like a good start to make these coercions available.

**Comment by kjetilk** [comment]
There is a bunch of these in [Types:URI](https://metacpan.org/release/Types-URI/source/lib/Types/URI.pm#L49) that I had forgotten about. We should look into if we should add to them, or perhaps add types to Attean.

**Comment by kasei** [comment]
Agreed. I've always hated the extra syntax of using the namespace objects to instantiate an `IRI`. I don't recall why we didn't do more with coercions in the past (and I seem to recall we did some but commented them out). I've been busy with work, but would be happy to merge a PR (re-)enabling coercions, or I can try to get to it slowly as I'm able.

**Comment by kjetilk** [comment]
These are now in Types::URI, so we can close this.
