### ISSUE TITLE
Tests depend on 5.14, module on 5.10.1

### ISSUE THREAD

**Issue by jwrightecs** [kasei/perl-iri#17]
test files t/base_resolution.t and t/rel.t include the line 'use 5.14;' preventing them from running on perl before 5.14, but the module itself only needs 5.10.1.   The 'use 5.14' seems unnecessary as they do not rely on any features in 5.12 or 5.14, and pass successfully once that line has been removed.  

This results in a module that can be installed on 5.10-5.12 as long as you install it without running tests (like Carton or cpanm's -n flag do)

See PR #18

**Comment by jwrightecs** [comment]
#18

**Comment by kasei** [comment]
Thank you.
